### ISSUE TITLE
Dynamic chart options

### ISSUE THREAD

**Issue by martinstannard** [ahmadsoe/ember-highcharts#1]
Currently ember-highcharts doesn't seem to have a way of updating in response to any change in chart options. We're sorting our data on the client side and would like to update the labels correspondingly. When we change the chart options content, for instance the axis labels, they don't update. If I drill down to the component via Ember Inspector and call .draw() on the component after the labels are updated, the new labels are drawn.

Given that chartOptions are usually a quite complex nested object, implementing observers on all properties is probably out. Do you think passing in a flag to the component that calls draw() when observed would be a reasonable solution? It would then be a matter of flipping the flag on the controller side to trigger the draw in the component. Or is there something I'm missing?

**Comment by lolmaus** [comment]
It seems that this is fairly simple to implement.

The only thing that i struggle to figure out is which Highcharts initialization options correspond to which Highcharts instance methods and their arguments.

**Comment by ahmadsoe** [comment]
@martinstannard please ignore my last comment about the `itemController`.  Have you found the good solution for this issue? maybe you could share your experience on this with us, as i have not tried it yet.

@lolmaus if we can "observers" on those options then we can just redraw the charts.

**Comment by martinstannard** [comment]
@ahmadsoe here's my simple implementation - https://github.com/martinstannard/ember-highcharts/commit/16e2d85f6d86d57f031626be0ad2e4e800320b61 and https://github.com/martinstannard/ember-highcharts/commit/5a76c20faec05944be20af55404380b677aead80.

Basically I've setup a flag which I observe and call drawLater whenever it changes. The main drawback is I have to manually toggle the flag within my app, but that keeps the implementation very simple.

**Comment by lolmaus** [comment]
@martinstannard: uhm, why don't you observe `chartOptions` directly? Just make sure to update it via `this.set`, then you don't need a weird custom property whose content does not reflect state.

**Comment by poteto** [comment]
As an aside, you can [redraw the chart](http://api.highcharts.com/highcharts#Chart.redraw) which should avoid any potential DOM thrashing:

```javascript
get(this, 'chart').redraw();
```

**Comment by martinstannard** [comment]
@lolmaus I could observe `chartOptions` but if I then only change one of values within the options, the observer will not fire. AFAIK there is no easy way within Ember to observe all the attributes of a object without up an observer for each attribute. Hence my admittedly ugly workaround.

@poteto - thanks for pointing out the `redraw` method. Looks like I should just call that instead of this hackery...

**Comment by lolmaus** [comment]
@martinstannard,

```js
var newObject = Ember.copy(this.get('somePlainObject'));
newObject.foo = 'bar';
this.set('somePlainObject', newObject);
```

I would suggest `propertyDidChange` instead of cloning the object, but it [doesn't work](https://github.com/emberjs/ember.js/issues/10661) for some reason. :(

**Comment by 20v100** [comment]
@martinstannard, did you settle on a solution? Did "get(this, 'chart').redraw();" worked for you? The title of my chart is "undefined" at initial rendering. I'm trying to redraw the chart after the title has been defined with no success.

**Comment by poteto** [comment]
@20v100 Sorry, I didn't mention that `.redraw()` (from the Highcharts API) only redraws when "changes have been done to the data or axis extremes", i.e. updating the title isn't a "redrawable" event. You will probably have to directly use [`get(this, 'chart').setTitle(...)`](http://api.highcharts.com/highcharts#Chart.setTitle) instead

**Comment by 20v100** [comment]
@poteto You are fantastic! Worked like a charm.

**Comment by gregjopa** [comment]
We have a similar use case where the chart subtitle and series name need to be dynamic. Is there a way to extend this component to call `setTitle()` when the content changes? @20v100 did you fork this repo to get setTitle() to work or were you able to extend this component?

I've tried the extending approach but it never changes the chart title. Here's my code:

```javascript
import Ember from 'ember';
import EmberHighChartsComponent from 'ember-highcharts/components/high-charts';

export default EmberHighChartsComponent.extend({

  dynamicContent: Ember.computed('content', function () {
    if (this.get('chart')) {
      var name = this.get('content')[0].name;
      this.get('chart').setTitle({ subtitle: name });
    }

    return this.get('content');
  })

});
```


Here's a simple demo of my use case that does not use ember: https://github.com/gregjopa/ember-reporting-example/tree/master/public/plain-js-app. My goal is to accomplish the same thing using ember-cli with this plugin.

**Comment by gregjopa** [comment]
I got this working by extending this component. Here's a working ember-cli app that dynamically updates the chart subtitle and series name with this addon: https://github.com/gregjopa/ember-reporting-example.

I took the approach of extending this component, observing changes to the model, then updating the chart titles, and redrawing the chart:

```javascript
import Ember from 'ember';
import EmberHighChartsComponent from 'ember-highcharts/components/high-charts';

export default EmberHighChartsComponent.extend({

  dynamicContent: Ember.computed('content', function () {
    var chart = this.get('chart');

    if (chart) {
      // when re-rendered update the chart subtitle and series name
      var repo = this.get('content')[0].name;
      chart.series[0].update({ name: repo }, false);
      chart.setTitle(null, { text: 'Repo: ' + repo }, false);
      chart.redraw();
    }

    return this.get('content');
  }),

  dynamicChartOptions: Ember.computed('chartOptions', function () {
    // when first rendered update the chart subtitle
    var repo = this.get('content')[0].name;
    this.get('chartOptions').subtitle.text = 'Repo: ' + repo;
    return this.get('chartOptions');
  })

});
``` 

However, there is a problem with this approach. I think chart.redraw() is getting called twice which screws up the chart animation. This addon redraws when the chart data changes using series.setData() and then my code also redraws to handle the title changes. Ideally we should only be redrawing once. 

Should this addon be responsible for handling updates to titles/labels? If not, can a config option be added to this addon to disable redrawing when the chart data changes and instead the developer is responsible for redrawing? The developer can handle redrawing when the data changes by extending this component. I'm happy to send a PR for this. Just need some guidance on which design to go with.

**Comment by ahmadsoe** [comment]
@gregjopa I think option to disable redrawing the chart is good to go.
I'm also happy to accept your PR if you want implement handling updates to title and axis label manually with Highcharts API.

**Comment by gregjopa** [comment]
@ahmadsoe I've been thinking more about this and I don't think a disable redrawing method is necessary. Instead, the `contentDidChange` method can be overridden by extending this addon. I sent PR #24 that adds documentation to the readme about how to use this approach.

Regarding adding logic to handle updates, I think there are quite a few use cases to handle series, axis, and title label changes. It may be best to keep this addon's codebase small and make the user override it to add custom redraw logic.

**Comment by ahmadsoe** [comment]
@gregjopa well, it seems best approach for now. I'm fine with this, as I rarely updates title or chart label on my apps :)

**Comment by gregjopa** [comment]
@ahmadsoe thanks for merging my PR. I think this issue can be closed since there is now a recommended approach for dynamic options documented in the readme. Also, here's an example ember app that shows how to extend this plugin: https://github.com/gregjopa/ember-reporting-example.

**Comment by ahmadsoe** [comment]
@gregjopa sure, thanks.

@martinstannard I'll close this issue for now, you could try @gregjopa 's approach for your problem.
