### ISSUE TITLE
Highcharts 5 support

### ISSUE THREAD

**Issue by Glennvd** [ahmadsoe/ember-highcharts#100]
Are there any plans to add highcharts 5 support in the near future? Some tests still seem to fail when using highcharts 5.0.0 instead of 4.2.7.

**Comment by gregjopa** [comment]
Yes, we'd like to support both v4 and v5 of HighCharts. It looks like v5 was released 6 days ago: https://www.npmjs.com/package/highcharts

I think the first step is documenting the breaking changes with v5 (test failures, dummy app failures).

**Comment by gregjopa** [comment]
I tested this addon with v5 and documented the problems in PR #102
