### ISSUE TITLE
Cannot read property high-charts of undefined

### ISSUE THREAD

**Issue by mikejerome** [ahmadsoe/ember-highcharts#108]
I tried extending the high-charts component to make a dynamic version like the example, but when I try to use it I get the error "Cannot read property high-charts of undefined". I copy-pasted the example dynamic-high-charts component exactly. This is ember 2.8

**Comment by gregjopa** [comment]
The "Overriding Chart Redrawing" code in the README doesn't work anymore (it worked before this commit: https://github.com/ahmadsoe/ember-highcharts/commit/adba0011e5a174ccf6a1bd76114188c4d7107286). Instead, try overriding the `didReceiveAttrs` method. Let me know if that works for you.

**Comment by mikejerome** [comment]
With the following code I get "cannot read property 'redraw' of null":

`export default EmberHighChartsComponent.extend({
 
    didReceiveAttrs() {
        this._super(...arguments);
        let chart = this.get('chart');
        chart.redraw();
    }
 
});
`

What I need to do is redraw the chart when the model changes, because the categories need to change in chartOptions.

**Comment by gregjopa** [comment]
I think there is a use case where `chart` is null with `didReceiveAttrs()` so we have this check in place (perhaps on initial render): https://github.com/ahmadsoe/ember-highcharts/blob/master/addon/components/high-charts.js#L53.

Also, have you seen the examples in the dummy app? Check out the interactive charts in the dummy app (https://ahmadsoe.github.io/ember-highcharts/). Does the "Update Series Data" button code help solve your use case? https://github.com/ahmadsoe/ember-highcharts/blob/master/tests/dummy/app/components/chart-line-interactive.js#L32. This code does not override anything. Just want to make sure you've seen this example before continuing down the override redraw path.

**Comment by mikejerome** [comment]
I don't think the example helps me. I'll try to explain my use case:

Template:
```
{{high-charts chartOptions=chartOptions content=chartData}}
```

Controller:
```
    chartData: Ember.computed('model', function() {
        return this.get('model.series');   
    }),
   chartOptions: Ember.computed('model', function() {
  return
        .....
        xAxis: {
            categories: this.get('model.categories')
        }
        ...
}),
```

The categories in this case are months: [jan, feb, mar, etc]. The user can click a dropdown to select a number of months of data to view, which sets a queryparam ?months=3 or ?months=6 etc which refreshes the model.

If months starts at 3, categories is [jan, feb, mar]. if 6 categories is [jan, feb, mar, apr, may, jun] etc. The problem is if the chart starts with 3 months, and then the user selects 6, the data in the chart is correct but the x-axis now looks like `jan | feb | mar | 3 | 4 | 5` instead of `jan | feb | mar | apr | may | jun` because the new chartOptions aren't being included.

Any idea how I could fix this?

**Comment by gregjopa** [comment]
I recommend managing your categories in chartData, not chartOptions. Highcharts is flexible and allows you to setup the category data either way. Here's an example:

Categories in chartOptions:
```js
chartOptions: {
  chart: {
    type: 'bar'
  },
  title: {
    text: 'Fruit Consumption'
  },
  xAxis: {
    categories: ['Apples', 'Bananas', 'Oranges']
  },
  yAxis: {
    allowDecimals: false,
    title: {
      text: 'Fruit eaten'
    }
  }
},

chartData: [
  {
    name: 'Jane',
    data: [5, 0, 20]
  },
  {
    name: 'John',
    data: [25, 30, 15]
  }
]
```

Categories in chartData:
```js

chartOptions: {
  chart: {
    type: 'bar'
  },
  title: {
    text: 'Fruit Consumption'
  },
  xAxis: {
    type: 'category'
  },
  yAxis: {
    allowDecimals: false,
    title: {
      text: 'Fruit eaten'
    }
  }
},

chartData: [
  {
    name: 'Jane',
    data: [
      ['Apples', 5],
      ['Bananas', 0],
      ['Oranges', 20]
    ]
  },
  {
    name: 'John',
    data: [
      ['Apples', 25],
      ['Bananas', 30],
      ['Oranges', 15]
    ]
  }
]
```

ChartData updates are dynamic so try moving your categories there. Hope this helps.

**Comment by mikejerome** [comment]
Nice, I think that's exactly what I need. I won't be able to try it until next week but it looks like it will work. Thanks so much for taking the time to help me.

**Comment by mikejerome** [comment]
That worked perfectly, thank you!
