### ISSUE TITLE
Uncaught Error: Highcharts error #16

### ISSUE THREAD

**Issue by fyaldiran** [ahmadsoe/ember-highcharts#109]
I use the ember packages below and I get the error #16. I use only HighCharts, not HighStock or HighMaps.

I also tried this settings but it does not work:
```
emberHighCharts: {
    includeHighCharts: true,
    includeHighStock: false
  }

```
  ```
 "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^2.4.1",
    "ember-cli": "2.11.1",
    "ember-cli-app-version": "^2.0.0",
    "ember-cli-babel": "^5.1.7",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-htmlbars": "^1.1.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.6",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-jshint": "^2.0.1",
    "ember-cli-qunit": "^3.0.1",
    "ember-cli-release": "^0.2.9",
    "ember-cli-shims": "^1.0.2",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.11.0",
    "ember-export-application-global": "^1.0.5",
    "ember-highcharts": "0.5.2",
    "ember-load-initializers": "^0.6.0",
    "ember-resolver": "^2.0.3",
    "ember-source": "~2.11.0",
    "ember-welcome-page": "^2.0.2",
    "highcharts": "^5.0.7",
    "loader.js": "^4.0.10"

```

**Comment by fyaldiran** [comment]
I get the error at `ember-cli@2.11.1`. I do not get the error at `ember-cli@2.7.0`. Is it possible for you to upgrade the ember-highcharts for ember-cli@2.11.1.

**Comment by ahmadsoe** [comment]
@fyaldiran still having issue on this? I just publish a new release with `ember-cli@2.11`

**Comment by fyaldiran** [comment]
Thanks @ahmadsoe but I still have the same error.

**Comment by aliseisaksen** [comment]
I've been getting Highcharts error #16 in my ember app as well. I narrowed it down to a likely forward-slash/back-slash issue. The image attached shows the Chrome Dev Tool Sources tab where you can see that `highcharts.src.js` gets loaded twice after building the ember app (I've highlighted both occurrences in the image below). Hopefully this helps.

![highcharts16](https://cloud.githubusercontent.com/assets/6486039/23963647/581b950e-0988-11e7-9965-5a1c42e14ae8.PNG)

**Comment by gregjopa** [comment]
I'm available to help with this. Can you reproduce this issue in a github repo or ember-twiddle?

**Comment by sandersoeteman** [comment]
I'm also getting this issue. Not on my mac develop machine, but only on the jenkins windows build server.

**Comment by gregjopa** [comment]
I will try to reproduce this on Windows. What version of Node and NPM are you using?

**Comment by deeksy** [comment]
For anyone looking at this issue on a windows machine, the fix that deathaz developed earlier is the one that you should use on Windows.  In the meantime, we've had to fork the project to incorporate
that fix as the pull request was rejected, but it is the correct way to get the ember-highcharts module to behave correctly on a Windows machine.
