### ISSUE TITLE
Deprecation: ember-getowner-polyfill.import

### ISSUE THREAD

**Issue by tniezurawski** [ahmadsoe/ember-highcharts#110]
I see the following deprecation:

DEPRECATION: ember-getowner-polyfill is now a true polyfill. Use Ember.getOwner directly instead of importing from ember-getowner-polyfill [deprecation id: ember-getowner-polyfill.import]

It probably comes from this file: `addon/components/high-charts.js`

**Comment by ahmadsoe** [comment]
try new release `0.5.3` the warning should be gone.

**Comment by tniezurawski** [comment]
Thanks! No more deprecation now.

I forgot to reply earlier! Can be closed ;)

**Comment by gregjopa** [comment]
Thanks for confirming.
