### ISSUE TITLE
DEPRECATION: Using "_lookupFactory" 

### ISSUE THREAD

**Issue by dzbo** [ahmadsoe/ember-highcharts#112]
With latest Ember Source 2.12.0 I get following deprecation:

```
DEPRECATION: Using "_lookupFactory" is deprecated. Please use container.factoryFor instead. [deprecation id: container-lookupFactory]
```

https://github.com/ahmadsoe/ember-highcharts/blob/master/addon/utils/option-loader.js#L7

Guess it's easy as `var localConfigBuilder = owner.factoryFor('highcharts-config:application');`

**Comment by ashypelskyi** [comment]
I have same error in my project, for Ember 2.12

**Comment by gregjopa** [comment]
I tried fixing this issue and I'm not able to get it to work with the new `owner.factoryFor()` method. It doesn't seem to return anything for me. Maybe I'm doing something wrong. Here's my feature branch commit with more details: https://github.com/gregjopa/ember-highcharts/commit/375cfc86cd7eeff6267a78ec215c2e3a30aac54a

This addon still supports Ember 1.13 so we need to use ember-getowner-polyfill: https://github.com/rwjblue/ember-getowner-polyfill. 

More details: https://emberjs.com/deprecations/v2.x/#toc_migrating-from-_lookupfactory-to-factoryfor

**Comment by gregjopa** [comment]
I went through the [RFC](https://github.com/emberjs/rfcs/blob/master/text/0150-factory-for.md) and realized that `factoryFor()` returns a different value than `_lookupFactory()`. It returns a factory and we can use the `class` property to get the highcharts config. Ex:
```js
let configFactory = owner.factoryFor('highcharts-config:application');
let localConfigBuilder = configFactory.class;
```

PR #117 fixes this issue.
