### ISSUE TITLE
Error in StockChart mode with navigator option enabled

### ISSUE THREAD

**Issue by mr-volevach** [ahmadsoe/ember-highcharts#114]
Hi.
When content for chart updated, I get error 
` TypeError: Cannot read property 'hoverSeries' of undefined`

I use ember 2.10, ember-highcharts 0.5.3. 
I set StockChart mode, and navigator option enabled
I have button for refresh data for chart. When I click button, will be send request and return new data. This data pass into highchart component.

I debug addon code and find

After data updated, ember will be run didReceiveAttrs.

       `
       if (isStockChart && series.name === 'Navigator') {
        return;
      }

      let contentSeries = contentSeriesMap[series.name];

      if (!contentSeries) {
        return chartSeriesToRemove.push(series);
      }`

After first update, this code will removes series for navigator, becouse series.name not equal "Navigator".

I find in highstock.src.js
`navSeriesMixin.name = 'Navigator ' + (i + 1);`

After second update, ember-highchart not find series for rerender navigator.

If you need any help in coding due to lack of time just give a sign :)
Thank you)

**Comment by aastein** [comment]
Same
