### ISSUE TITLE
Too many default options?

### ISSUE THREAD

**Issue by trentmwillis** [ahmadsoe/ember-highcharts#12]
This is just a thought, but are most of the default options really needed? I think stuff like setting the timezoneOffset and turning credits off are useful, but all the color options and font-related things are a bit thematic and should be the responsibility of the user and not the add-on.

By leaving them in, we also increase file-weight and a good portion of which has the potential of being overwritten by the user.

Plus, Highcharts looks pretty good with [few options passed in](http://jsfiddle.net/ueyqo2dm/).

I'm thinking of submitting a PR to reduce the number of default styles and probably move them to a separate (and optional) theme file. Thoughts?

**Comment by ahmadsoe** [comment]
Yes, I think we can remove the default themes on this addon and move them to a separated theme file, so we can add [additional themes](https://github.com/highslide-software/highcharts.com/tree/master/js/themes) later and give the user options to includes one or more of those themes. It'd be very nice for this addons. 

Looking forward to your PR! :smile:

**Comment by huiyuan** [comment]
Hey @ahmadsoe , I work with @trentmwillis and since he's quite busy right now, I'll be working on the PR. Will have one soon!

**Comment by ahmadsoe** [comment]
Closed in #13
