### ISSUE TITLE
Updating the data issue

### ISSUE THREAD

**Issue by introvert** [ahmadsoe/ember-highcharts#127]
Hey,

I'm not sure I'm getting this addon in the right sense. I would like to use it for simplified drawing of charts, but when I set the variable that is assigned to the content, it won't update the graph.

Regarding using the Dynamic Chart example - I'm not entirely sure how this is supposed to work - I guess I should still come {{highcharts ...}} component within the dynamic chart's template?

Any example to dynamically change the content of the graph would be highly appreciated.

**Comment by shankarsridhar** [comment]
@introvert Do you mind providing an ember-twiddle to demonstrate the problem ?
