### ISSUE TITLE
Broken npm package

### ISSUE THREAD

**Issue by lolmaus** [ahmadsoe/ember-highcharts#14]
> The `ember-highcharts` addon could not be found at `<project_path>/node_modules/ember-highcharts`.

To reproduce:

1. Remove the `ember-highcharts` entry from `package.json`.
2. Remove the `ember-highcharts` subfolder from the `node_modules` folder.
3. Run `npm cache clean`.
4. Run `npm install --save-dev ember-highcharts`, which would install version `0.0.7` as of 2015-03-11.
5. Run `ember s`.

You'll see the error and Ember will not start.

I can see that `node_modules/ember-highcharts` lacks an `index.js`.

At the same time, when i use `0.0.5` or `git://github.com/lolmaus/ember-highcharts.git` (my fork for #9) as `ember-highcharts` version, Ember runs fine.

**Comment by ahmadsoe** [comment]
Should fixed by new version

**Comment by lolmaus** [comment]
Works now, thank you! :+1: 

Was it the existence of the `gh-pages` folder to blame? O_o
