### ISSUE TITLE
Release 0.7.0 to npm

### ISSUE THREAD

**Issue by lamabiker** [ahmadsoe/ember-highcharts#140]
Hi Guys, thanks for the release, but it appears that 0.7.0 hasn't been published to the npm registry, still on 0.6.0 https://www.npmjs.com/package/ember-highcharts

Could you publish it to npm please? Thanks!

**Comment by nlfurniss** [comment]
https://github.com/ahmadsoe/ember-highcharts/pull/139#issuecomment-382813465

**Comment by lamabiker** [comment]
Thanks, I hadn't read that comment!

**Comment by ahmadsoe** [comment]
@lamabiker I just published it to npm.
Sorry for the delay.
