### ISSUE TITLE
Theme does not work as is worked before 0.7

### ISSUE THREAD

**Issue by bortevik** [ahmadsoe/ember-highcharts#142]
Replacing jquery `extend(true, ...)` to ember `assign` in `buildOptions` broke themes in our app. I think this the case for others as well.

**Comment by nlfurniss** [comment]
@bortevik Thanks for reporting, will put a fix out

**Comment by nlfurniss** [comment]
@bortevik this is fixed in `1.0.1` - please check it out and sorry for the bug!
