### ISSUE TITLE
How to hook the click event in ember

### ISSUE THREAD

**Issue by balajee** [ahmadsoe/ember-highcharts#147]
could someone help me how to add the click event in ember-highcharts? my requirement is, when someone click the point i need to display some table below the sankey highchart. So wondering how to call my ember action into this code

`plotOptions: {
        series: {
          cursor: 'pointer',
          point: {
            events: {
              click: function () {
                // will be showing some table based on clicked point
              }
            }
          },`

**Comment by Baltazore** [comment]
Hey @balajee you can use computed for your chart options and send proper click function
```
chartOptions: computed('onUnitClick', function() {
    return {
      chart: {
        type: 'column'
      },
      title: {
        text: 'by Unit'
      },
      xAxis: {
        categories: ['Unit 5', 'Unit 1', 'Unit 3', 'Unit 4', 'Unit 2']
      },
      yAxis: {
        title: {
          text: 'Alerts Number'
        }
      },
      plotOptions: {
        column: {
          stacking: 'normal',
          dataLabels: {
            enabled: true,
            color: 'white'
          }
        },
        series: {
          cursor: 'pointer',
          events: {
            click: this.get('onUnitClick')
          }
        }
      },
    }
  }),
```

Something like this. I hope it helps. Please close issue after verification

**Comment by balajee** [comment]
i got the fix. and below is the code which i used.

`chartOptions: computed(function() {
    let that = this;
    return {
      chart: {
        type: 'column'
      },
      title: {
        text: 'by Unit'
      },
      xAxis: {
        categories: ['Unit 5', 'Unit 1', 'Unit 3', 'Unit 4', 'Unit 2']
      },
      yAxis: {
        title: {
          text: 'Alerts Number'
        }
      },
      plotOptions: {
        column: {
          stacking: 'normal',
          dataLabels: {
            enabled: true,
            color: 'white'
          }
        },
        series: {
          cursor: 'pointer',
          point: {
            events: {
              click: function () {
                if (!isEmpty(this.id)) {
                  that.set('something',this.id);
                }
              }
            }
          }
        }
      },
    }
  }),`
