### ISSUE TITLE
Should bootstrap be in devDependencies?

### ISSUE THREAD

**Issue by paulcwatts** [ahmadsoe/ember-highcharts#148]
I noticed that `bootstrap` is defined in `dependencies` in `package.json`, which creates a dependency on that in the host app. It appears that bootstrap is only used in the dummy app -- should this rather be in `devDependencies`?

I am happy to file a PR if this is the case. I've also seen addons not include Bootstrap in `package.json` at all, and instead include the CSS directly from the Bootstrap CDN. I could also do that and remove this dependency entirely.

**Comment by nlfurniss** [comment]
As I understand it, whether it's in devDeps or regular deps, code is only pulled into the host app if it is referenced. So while you'll find Boostrap in this addon's asset after doing `ember build`, you won't find it in your host app's css files.

**Comment by paulcwatts** [comment]
Yes, it's true it doesn't appear in the host app's CSS bundle. When I said "dependency" I meant that it appears in my host app's `yarn.lock` file. So it's mostly just a one line change to specify this addon's dependencies more appropriately.

**Comment by acorncom** [comment]
@nlfurniss any **objections** to putting the `bootstrap` dependency in `devDependencies`? For folks already using bootstrap this has the potential of causing headaches ...

**Comment by Techn1x** [comment]
Any chance we could do a minor release with this change? Have been waiting patiently for 6 months for a release :)
