### ISSUE TITLE
Is it possible to load plugins?

### ISSUE THREAD

**Issue by Mithrilhall** [ahmadsoe/ember-highcharts#154]
Is it possible to load plugins? Such as [custom-events](https://www.highcharts.com/products/plugin-registry/single/15/Custom-Events)?

**Comment by vinicius5581** [comment]
@Mithrilhall, have you figured this out? I'm looking for the same answer.

**Comment by Mithrilhall** [comment]
@vinicius5581 I was able to load the custom events. Unfortunately I lost the code. I believe I loaded it via ember-cli-build.js.
