### ISSUE TITLE
Highcharts xrange mode

### ISSUE THREAD

**Issue by lukkor89** [ahmadsoe/ember-highcharts#155]
Hi,
is it possible to use xrange mode in this ember-highcharts component? I'm having trouble because to get it work I had to update my highcharts library to 6.1.0 but I see that's Your component not using highcharts greater than 5... If I update my highcharts library in Ember Project I'm getting chart issues, previous charts stop working cause chart instance is undefined. Updating highcharts also cause problem with autofit chart to container... Could You help me with this?

**Comment by nlfurniss** [comment]
What version of Highcharts did you try to upgrade to? Can you provide a gist with the stacktraces of the errors you were seeing?

**Comment by lukkor89** [comment]
I was using highcharts in version "^6.2.0" and updated to "highcharts": "^7.0.1". I see they've started to use container for charts that I ve been missing in my handlebars. I have just wondering if there is possible to use xrange mode at all, because You didn't mention about it in docs:

> includeModules: ['map', 'broken-axis', 'heatmap', ... ]
>     /* available modules:
>       boost, broken-axis, canvas-tools, data, drilldown, exporting, funnel,
>       heatmap, map, no-data-to-display, offline-exporting, solid-gauge, treemap
>     */

**Comment by nlfurniss** [comment]
Do you know when xrange was added to handlebars? Can you link to xrange in the highcharts docs?

**Comment by nlfurniss** [comment]
@lukkor89 all you need to do is add `xrange` to the `includeModules` [here](https://github.com/ahmadsoe/ember-highcharts#configuration), and set the chart type tp xrange

ex:
```javascript
  chartOptions = {
    chart: {
      type: 'xrange'
    },
```

I modified the example basic bar chart in the dummy app as a demo
![image](https://user-images.githubusercontent.com/1477357/128577178-7faf24f0-f6c1-49ab-9e41-8809a453b7c1.png)
