### ISSUE TITLE
Cannot read property "forExport" of undefined

### ISSUE THREAD

**Issue by Skank22** [ahmadsoe/ember-highcharts#161]
when I go to another page there is an error, before that the graphics worked
[http://prntscr.com/ns7oi7](http://prntscr.com/ns7oi7)
and my code,
[http://prntscr.com/ns7nba](http://prntscr.com/ns7nba)

**Comment by nlfurniss** [comment]
The error is coming from the highcharts library itself. Can you give more details about `before that the graphics worked`; did you update ember-highcharts?

**Comment by guitassinari** [comment]
I am having that same problem. It happens when I try to render a component that extends from `ember-highcharts/components/high-charts`

**Comment by Skank22** [comment]
the error appears when to move on another page

**Comment by nlfurniss** [comment]
Please update to the latest version of this addon and reopen this issue if there's still an issue
