### ISSUE TITLE
Replacing xAxis, and yAxis

### ISSUE THREAD

**Issue by clarencejychan** [ahmadsoe/ember-highcharts#181]
I'm looking to dynamically update the x and y axis along with the data. I see that there's already the capability to redraw the graph when new data is loaded, but using `setAxis` on the highcharts API doesn't seem to work for x and y axis. Is there some way to do this?

**Comment by nlfurniss** [comment]
@clarencejychan these are x and y axis options that are set when you create the chart, but that you want to update later?

can you modify one of Highchart’s js fiddle examples to show what you’re trying to do?

**Comment by RobbieTheWagner** [comment]
Since this is an old issue, I am going to close it for now. If you are able to provide an example, we can look at supporting this. Thanks!
