### ISSUE TITLE
Enable end-user to attach callback functions

### ISSUE THREAD

**Issue by huiyuan** [ahmadsoe/ember-highcharts#19]
@ahmadsoe , I wonder if there is a convenient way for end-user to attach callback functions? If not, it's potentially can be done by extending the current 'options' with a callback parameter like this

In the draw() function: 
let options = [ get(this, 'buildOptions'), get(this, 'callbacks') ]; 
We could rename 'options' here accordingly.

If you think this is a good approach, I will submit a PR for it.

**Comment by ahmadsoe** [comment]
what kind of callback? you have example use case?

**Comment by lolmaus** [comment]
E. g. selecting a sector in a pie chart.

**Comment by ahmadsoe** [comment]
Highcharts have [selection event](http://api.highcharts.com/highcharts#chart.events.selection) and other events that you can pass it via charts options. I think you can attach your callback in there.

**Comment by huiyuan** [comment]
I would like to render a new path. Like this

**Comment by huiyuan** [comment]
It's the callback functions we pass in when initializing the chart. I'd like to add some customized components after the chart is rendered.  Like this example: 

$('#container').highcharts(options, function(chart) {
    // Add a new path and an image
    chart.renderer.path([....]).add();
    chart.renderer.image(...).add();
});

Currently, the options is wrapped by an array as the arguments and we can't pass in the second argument which is the callback function. Please see the code below.

let options = [ get(this, 'buildOptions') ];
....
let chart    = $element.highcharts.apply($element, options).highcharts();

If we use

let options = [ get(this, 'buildOptions'), get(this, 'callback') ]; 

The user can then extend the addon and provide a callback function.

**Comment by ahmadsoe** [comment]
Its seem like callback for [load event](http://api.highcharts.com/highcharts#chart.events.load). But, since highcharts support the second parameter, we should too.. I'd happy to accept this.

**Comment by ahmadsoe** [comment]
Closed in #22
