### ISSUE TITLE
Highmaps

### ISSUE THREAD

**Issue by chrisbenson** [ahmadsoe/ember-highcharts#2]
It would be amazing if this Ember-CLI addon included Highmaps too.  Are there any plans to include maps?  Thanks!

**Comment by lolmaus** [comment]
I ran into a necessity to use Highstock.

I think i'm able to create a PR, but i will have to remove `addBowerPackageToProject('highcharts-release#~4.0.4')` and `app.import(app.bowerDirectory + '/highcharts-release/highcharts.js');`.

It will be up to user whether to import Highcharts, Highstock and/org Highmaps, which are distributed from separate repos. I will add instructions to the readme.

@ahmadsoe Shall i proceed?
