### ISSUE TITLE
themes folder not installed

### ISSUE THREAD

**Issue by lmcardle** [ahmadsoe/ember-highcharts#23]
I am new to this component and just trying it out.  My understanding is that after running:

    ember install:addon ember-highcharts

I should have a themes folder, however there is none.  As such importing the theme in a controller fails with the error 'could not find module ../themes/default-theme.

**Comment by trentmwillis** [comment]
By default, I don't think the add-on provides any themes at the current time. The examples given are just to show how you could import your own theme. For an example of how to define a theme, [take a look in the dummy app](https://github.com/ahmadsoe/ember-highcharts/blob/master/tests/dummy/app/themes/default-theme.js); you then just have to import it. Hope that helps!

**Comment by lmcardle** [comment]
Thanks...that makes sense.  :)

Another quick question, the docs say that the addon includes "blueprints to easily create sub-classes."  However, I get the error "Unknown blueprint: chart" when running:

    ember generate chart my-chart

**Comment by trentmwillis** [comment]
Looks like there hasn't been a new version release since that feature was added. @ahmadsoe, think you could bump the version to include the blueprints (and any other recent additions)?

**Comment by ahmadsoe** [comment]
Just published a new version, feel free to re-open if you're still having issues.
