### ISSUE TITLE
Missing option to include highcharts-more.js vendor file

### ISSUE THREAD

**Issue by gregjopa** [ahmadsoe/ember-highcharts#25]
The highcharts-more.js file is required for rendering certain chart types like the waterfall chart: http://www.highcharts.com/demo/waterfall. Here's the highcharts download page that shows this highcharts-more.js file: http://code.highcharts.com/

Would you be open to adding an additional config option for this? Ex:

```javascript
var app = new EmberApp({
  emberHighCharts: {
    includeHighCharts: false,
    // new config option
    includeHighChartsMore: true,
    includeHighStock: true,
    includeHighMaps: false
  }
});
```

If so, I can send a PR to add this `includeHighChartsMore` option.

**Comment by ahmadsoe** [comment]
Sure, I'd be happy to accept this.
