### ISSUE TITLE
I think v3.2.0 should have been a major version

### ISSUE THREAD

**Issue by kellyselden** [ahmadsoe/ember-highcharts#278]
It won't work in apps unless they add ember-auto-import v2

```
Error: To use these addons, your app needs ember-auto-import >= 2: ember-highcharts
```

I recommend reverting the change, releasing as 3.2.2, and then reapplying the change as v4.0.0.

**Comment by Techn1x** [comment]
was coming here to post the same ^

**Comment by Techn1x** [comment]
also from https://github.com/ef4/ember-auto-import/blob/main/docs/upgrade-guide-2.0.md#apps-responsible-for-installing-webpack

> Addons that use ember-auto-import 2.0 should not put webpack into dependencies (the app's version will be used instead). They will need it in devDependencies in order to build their own dummy app.

might need to move webpack to devdeps.

**Comment by kdagnan** [comment]
Agreed, especially considering ember-auto-import is now imposing webpack as a **requirement** and dropping support for node < 12.

**Comment by Techn1x** [comment]
@nlfurniss @ahmadsoe any chance we can get this rectified?
