### ISSUE TITLE
Check that a chart exists before calling destroy.

### ISSUE THREAD

**Issue by jscadden** [ahmadsoe/ember-highcharts#28]
Need to check for a chart before calling destroy. Otherwise we can get the following error:
Uncaught TypeError: Cannot read property 'destroy' of null

**Comment by ahmadsoe** [comment]
@jscadden how did you catch this issue?

**Comment by jscadden** [comment]
Good question.  I have an odd case where my application caused a reload of the view before the component had finished rendering (The didInsertElement hadn't ran yet).  So it called the willDestroyElement before a chart could be created.  This issue may be a sign that something else is a problem with the flow of rendering in my application.

**Comment by jscadden** [comment]
I have forked the repo and made a couple changes to get around the issue for now.  I am also working on upgrading to Ember 1.13.  I believe the new component lifecycle hooks will help in my situation as well.

**Comment by 20v100** [comment]
I'm having the same error. I'm on ember 1.13.3. Seem that destroy was ran before the component finished updating. This solved the issue:

    _destroyChart: on("willDestroyElement", function () {
      this._super();
      if (!!this.get("chart")) {
        get(this, "chart").destroy();
      }
    })

**Comment by ahmadsoe** [comment]
I have some application using this component on ember 1.13.3 too and its working fine without problems.

If  `willDestroyElement` was ran before `didInsertElement`, then there must be something wrong with your application or ember itself.

**Comment by ahmadsoe** [comment]
@jscadden I just merged PR #29. Let me know if you had any news on this.
