### ISSUE TITLE
No way to change global theme

### ISSUE THREAD

**Issue by zhuoqiang** [ahmadsoe/ember-highcharts#3]
It seems no public API to change the default global theme, like color, font. Or do I miss anything?

**Comment by ahmadsoe** [comment]
You can change the default theme in `chartOptions`.
```javascript
chartOptions: {
  title: {
    style: {
      color: '#333333', // change title color
      fontSize: '20px' // change title fontsize
      ...
     }
  }
}
```

**Comment by zhuoqiang** [comment]
Yes, the individule chart theme could be override by `chartOptions`. 

However, what I would like is to override the default theme for ALL charts.

In highcharts you could override it very easily. However, it seems ember-highcharts always override the global highcharts settings. It would be convenience to let user override the global settings instead of modify chartOptions one by one when when there are many chart components.
