### ISSUE TITLE
How can one use Annotation module of highchart using ember-highcharts?

### ISSUE THREAD

**Issue by Abhinav1801** [ahmadsoe/ember-highcharts#308]
I have read the doc and I understand that "content" param of <HighCharts> tag relates to "series" of highcharts. But I want to use "annotations" from highcharts. Is there a way to do this?

**Comment by nlfurniss** [comment]
Have you tried to load the module as outlined in the readme?

https://github.com/ahmadsoe/ember-highcharts#configuration
