### ISSUE TITLE
Getting https://assets.highcharts.com/errors/16/ error on EmberJS application

### ISSUE THREAD

**Issue by Abhinav1801** [ahmadsoe/ember-highcharts#309]
Hello,

I am using ember-highcharts: ^1.2.0 along with highcharts: ^6.2.0 and my ember-highcharts configuration looks like this in ember-cli-build.js:

emberHighCharts: {
includeHighStock: true,
includeHighCharts: false,
includeModules: [
'solid-gauge',
'no-data-to-display',
'histogram-bellcurve',
'treemap',
'heatmap',
],
},

I want to use flag series from HighStock and I read on ember-highcharts docs that since HighStock already Highchart I need to keep includeHighStock: true and includeHighCharts: false but even after doing this I am getting https://assets.highcharts.com/errors/16/ error and some ember-resolver error (even though I have ember-resolver installed).

Please help me with anything you can.

**Comment by RobbieTheWagner** [comment]
@Abhinav1801 did you ever resolve this? I have heavily refactored things now to not need the config at all, so perhaps it will work now. If not please feel free to reopen this!

**Comment by Abhinav1801** [comment]
Hey Robbie,

Thank you so much for your support!  This was a long long time and I think
I was able to resolve it (maybe it was a work around for the specific
requirement that I tried).

Again, thanks for the update.

Regards,
Abhinav
