### ISSUE TITLE
Highcharts does not include the drilldown module

### ISSUE THREAD

**Issue by petey** [ahmadsoe/ember-highcharts#31]
I'm trying to make a drilldown chart, and the drilldown module does not seem to be part of the highcharts source.

http://api.highcharts.com/highcharts#drilldown

**Comment by Datamance** [comment]
@ahmadsoe  Sorry, can you leave a bit more explicit direction on this? I'm still not understanding why I can't drill down on my pie graph even with Highcharts' example code... should I include highcharts3d or highcharts more?

**Comment by gregjopa** [comment]
@Datamance I just tried to implement a drilldown chart using this addon and I don't think it's currently possible. I opened up this issue with the details #76.

**Comment by Datamance** [comment]
@gregjopa  thanks so much for the quick update!

@ahmadsoe are there any workarounds in the meantime that you might suggest (other than just using the plain pie graphs)? The drilldown feature is a super super-elegant way to conserve screen real estate in things like dashboards...

**Comment by gregjopa** [comment]
@Datamance Good news. I was wrong. You can implement a drilldown chart with this addon. You just need to include the `drilldown` option in the `chartOptions` argument (previously I was trying to include it in the `content` argument which is incorrect). 

Check out PR #77 which includes a demo of how to implement a drilldown chart with this addon.

**Comment by Datamance** [comment]
@gregjopa thanks! Good to know that it works... I still seem to be encountering issues, however.

In specific, I get this error after copy-pasting the controller code:

Error while processing route: index Cannot read property '_qpMap' of undefined TypeError: Cannot read property '_qpMap' of undefined

any idea what could be going on? It also seems like you're miosing a "chartMode" stanza in the root level of the controller config (sibling to chartOptions)
