### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by JohnRodney** [ahmadsoe/ember-highcharts#34]
First thanks for the repo this addon is very nice to work with.  In my app I had need for the solid gauge which isn't included in your module.  

I made some adjustments and was able to get in in my app and working would you be willing / interested in me doing a PR to add this module to your repo or which you prefer that I forked the repo and just published my own NPM addon for the app I'm working with?

**Comment by stefanlyew** [comment]
+1

**Comment by yanzixiang** [comment]
+2

**Comment by JohnRodney** [comment]
Thanks for this I'll test it in my environment.
