### ISSUE TITLE
Theme?

### ISSUE THREAD

**Issue by fullofcaffeine** [ahmadsoe/ember-highcharts#35]
Hi!

Wondering where do you get the theme from, in the sample provided when you import it?

```javascript
import defaultTheme from '../themes/default-theme';
```

**Comment by ahmadsoe** [comment]
see here https://github.com/ahmadsoe/ember-highcharts/blob/master/tests/dummy/app/themes/default-theme.js

**Comment by gregjopa** [comment]
The ember-reporting-dashboard repo is another example of using a theme with this addon:
- https://github.com/gregjopa/ember-reporting-dashboard/blob/master/app/themes/theme.js
- https://github.com/gregjopa/ember-reporting-dashboard/blob/master/app/pods/components/chart-stacked-area/component.js#L2

I think this issue can be closed.
