### ISSUE TITLE
Replace `ember-holy-futuristic-template-namespacing-batman` with `ember-template-imports`

### ISSUE THREAD

**Issue by charlesfries** [ahmadsoe/ember-highcharts#369]
[Ember global usage ](https://github.com/rwjblue/ember-holy-futuristic-template-namespacing-batman/blob/master/vendor/service-inject-4.js) in that addon is making our Ember 4 upgrade painful. It is now apparently recommended to use `ember-template-imports` over the former.

I'll submit a PR when I have time.

**Comment by RobbieTheWagner** [comment]
I don't think we need either of them, right?

**Comment by charlesfries** [comment]
Yeah. Looks like neither is used.
