### ISSUE TITLE
A usable example using ember

### ISSUE THREAD

**Issue by greggawatt** [ahmadsoe/ember-highcharts#4]
Do you have a useable example using ember-cli? It would be nice to see how this plugs in exactly as I have just spent 2 hours attempting to do just that with no progress.

**Comment by Dhaulagiri** [comment]
@greggawatt I made a sample repo [here](https://github.com/Dhaulagiri/ember-highcharts-sample-app).  Do note though that I did fork `ember-highcharts` and make some updates to it, so you may need to pull the [fork](https://github.com/Dhaulagiri/ember-highcharts) down and link it locally for my sample app to work.

**Comment by Dhaulagiri** [comment]
Looks like my sample app should work linked against this repo as is

**Comment by ahmadsoe** [comment]
@greggawatt the implementation of this addon is very simple, just like another ember components. If you still stuck on this, you can see @Dhaulagiri's sample repo or post your code here see if I can help.

@Dhaulagiri i see you make some updates, it would be awesome if you can pull those changes to this repo.

**Comment by Dhaulagiri** [comment]
Opened #5 to pull in my changes

**Comment by ahmadsoe** [comment]
take a look at 373460131ee684eaf93bebe9226534d9b397b096 and live demo http://ahmadsoe.github.io/ember-highcharts/
