### ISSUE TITLE
Ember 2.1.0 container api compatibility

### ISSUE THREAD

**Issue by flaviooliveri** [ahmadsoe/ember-highcharts#41]
container.optionsForType was removed in Ember 2.1.0. The initializer is throwing an error because of that. I guess it should be changed to container.registerOptionsForType

**Comment by gregjopa** [comment]
I get the same error with Ember 2.1.0.

**Comment by ahmadsoe** [comment]
Would you guys mind submitting a PR?

**Comment by gregjopa** [comment]
I just submitted a PR - #42

**Comment by ahmadsoe** [comment]
closed in PR #42
