### ISSUE TITLE
 Highcharts[constr] is not a function

### ISSUE THREAD

**Issue by teckays** [ahmadsoe/ember-highcharts#43]
I have this error using the default setup as provided in this repo 
`highmaps.src.js:995 Uncaught TypeError: Highcharts[constr] is not a function`

**Comment by ahmadsoe** [comment]
@teckays you need to include HighCharts to the build.

**Comment by drapergeek** [comment]
I'm seeing the same thing. I added:

```javascript
    emberHighCharts: {
      includeHighCharts: true,
    },
```

to my `ember-cli-build.js` and the highcharts.js is being included, I see it in the inspector.

**Comment by aalimovs** [comment]
Same here with ```emberHighCharts``` in ```ember-cli-build.js```

**Comment by aalimovs** [comment]
If you remove ```chartMode: 'StockChart'```, it works and renders the chart.

**Comment by ahmadsoe** [comment]
If you set `chartMode` to `StockChart` or `Map`, you have to include Highstocks or Highmaps to the build.
```
// ember-cli-build.js
emberHighCharts: {
  includeHighCharts: false,
  includeHighStock: true,
  includeHighMaps: true
}
```

**Comment by ahmadsoe** [comment]
@teckays closing this, feel free to reopen if you still experience any problems.

**Comment by drapergeek** [comment]
@ahmadsoe thanks for the reply. Can I recommend adding that information to the README?
