### ISSUE TITLE
Release v3.2.2 for assign polyfill deprecation

### ISSUE THREAD

**Issue by raido** [ahmadsoe/ember-highcharts#434]
Importing assign() from ember/polyfills is deprecated.

Fix for this has been also merged but is not released to NPM - https://github.com/ahmadsoe/ember-highcharts/commit/2c9b009b1f50d9ae1a5e8ede6e9653fe222555b8

Would it be possible to rollout v3.2.2?

**Comment by kdagnan** [comment]
@ahmadsoe Could you release a 3.2.2 with this change? We can't use with Ember 5.X currently.

**Comment by RobbieTheWagner** [comment]
Looks like this was released, so closing this.
