### ISSUE TITLE
Solidgauge not working 

### ISSUE THREAD

**Issue by temecom** [ahmadsoe/ember-highcharts#44]
I tried to create a solid gauge: 
* Added the solidgauge option to ember-cli-build.js: 

 var app = new EmberApp(defaults, {
    // Add options here
    emberHighCharts: {
        includeHighCharts: false,
        includeHighStock: true,
        includeHighMaps: false,
        includeHighChartsMore: true,
        includeHighCharts3D: false,
        includeModules: ['solid-gauge', 'canvas-tools']
         }
  });

* Added a controller with code from highcharts solid gauge example: 

import Ember from 'ember';
import defaultTheme from '../themes/default-theme';
export default Ember.Controller.extend({
chartMode: 'StockChart', // Available options: a falsy value, 'StockChart', 'Map'.
                           // If `mode` is not provided or is a falsy value, the chart is initialized in Charts mode.
                           // If `mode` is a string, it is passed to Highcharts as the first argument.
                           // When Highcharts introduces a new mode, you will be able to use it here right away.

  chartOptions: {
    chart: {
                type: 'solidgauge'
            },

            title: null,

            pane: {
                center: ['50%', '85%'],
                size: '140%',
                startAngle: -90,
                endAngle: 90,
                background: {
                    backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || '#EEE',
                    innerRadius: '60%',
                    outerRadius: '100%',
                    shape: 'arc'
                }
            },

            tooltip: {
                enabled: false
            },

            // the value axis
            yAxis: {
                stops: [
                    [0.1, '#55BF3B'], // green
                    [0.5, '#DDDF0D'], // yellow
                    [0.9, '#DF5353'] // red
                ],
                lineWidth: 0,
                minorTickInterval: null,
                tickPixelInterval: 400,
                tickWidth: 0,
                title: {
                    y: -70
                },
                labels: {
                    y: 16
                }
            },

            plotOptions: {
                solidgauge: {
                    dataLabels: {
                        y: 5,
                        borderWidth: 0,
                        useHTML: true
                    }
                }
            },

  theme: defaultTheme
  }
});

  but am getting: 

Uncaught Highcharts error #16: www.highcharts.com/errors/16error @ highstock.src.js:701(anonymous function) @ highstock.src.js:108(anonymous function) @ highstock.src.js:23760
loader.js:110
Uncaught Error: Could not find module `ember-cli-app-version/initializer-factory` imported from `dali-gauge/initializers/app-version`

It is probably a configuration issue but the documentation covers only the simplest charts and the error code is not explicit enough to help. 

I am happy to contribute a solution with a little guidance. 

Thanks

Chris

**Comment by ahmadsoe** [comment]
It should be working fine if you remove `canvas-tools` from `includeModules` options. I just found out that canvas-tools module isn't supposed to be included in the build. 
See https://github.com/highslide-software/highcharts.com/issues/2311#issuecomment-25685317

**Comment by SirZach** [comment]
For anyone else that comes here looking for a solution, double check to make sure you spelled it as "gauge" and not "guage". D'oh!

**Comment by ahmadsoe** [comment]
@temecom I'll close this issue, feel free to reopen if you still have a problem with solid gauge module.
