### ISSUE TITLE
Not proper data updating

### ISSUE THREAD

**Issue by goloveychuk** [ahmadsoe/ember-highcharts#47]
https://github.com/ahmadsoe/ember-highcharts/blob/master/addon/components/high-charts.js#L57
Should add line
var toRemove chart.series.length - this.get('content').length
while (toRemove > 0) {
  chart.series[chart.series.length-1].remove(); //smth line this
  toRemove -= 1;
}
Maybe highchart already have method for this.

**Comment by gregjopa** [comment]
Can you provide an example showcasing this problem? I don't understand why this fix is needed.

**Comment by goloveychuk** [comment]
As I remember, If you set an empty array to content, addon don't remove existing series, but should.

**Comment by ahmadsoe** [comment]
I can confirm this, removing one or more data from `contentData` not updating the chart.

Would you mind submitting a PR?

**Comment by goloveychuk** [comment]
@ahmadsoe don't work on highcharts project and don't know their api, so, sorry, but not, I don't going to PR.

**Comment by thijsvdanker** [comment]
I have created a custom component that updates some things (series, xAxis and resets colors).
I've made a gist here that could be the starting point of a patch or of use to someone else:
https://gist.github.com/thijsvdanker/e43ad9dbe4fc50a8b2c9

**Comment by gregjopa** [comment]
I noticed that @poteto updated her highcharts-component.js gist which may address this issue: https://gist.github.com/poteto/cd2bb47e77bf87c94d33#file-highcharts-component-js-L34.

I'm going to work on creating a test page for this use case w/ dynamically changing the number of series in a dataset.
