### ISSUE TITLE
Blueprints?

### ISSUE THREAD

**Issue by MichalBryxi** [ahmadsoe/ember-highcharts#477]
In [this part of README.md](https://github.com/ahmadsoe/ember-highcharts/blob/master/README.md?plain=1#L154) it is said that there a blueprints available:

```sh
> ember generate chart <chart-name>
```

but in [this commit](https://github.com/ahmadsoe/ember-highcharts/commit/513cd4f440ed9bd78fb51c08abb7a65d5f755ce8#diff-b1e221bd5a096866f8ecfccb2c7d04c7f758878ffe9c3b3f2f0fe515d8cb6bd0) (converstion to v2 addon) the blueprints seem to be deleted.

Moreover when I try running said line I will get:

```sh
> pnpm exec ember generate chart time-series
Unknown blueprint: chart
```

Should we:

1. Delete said reference as it's no longer up-to-date?
2. Delete all other (linting, gitignore, etc.) [references to blueprints](https://github.com/search?q=repo%3Aahmadsoe%2Fember-highcharts%20blueprints&type=code)?

**Comment by RobbieTheWagner** [comment]
@MichalBryxi I don't think v2 addons support blueprints, so we should probably remove reference to them.

**Comment by MichalBryxi** [comment]
Cool. Here ya go: @RobbieTheWagner https://github.com/ahmadsoe/ember-highcharts/pull/484
