### ISSUE TITLE
Modules support Need to be Specific for Stock Charts

### ISSUE THREAD

**Issue by lvanngo** [ahmadsoe/ember-highcharts#48]
Hi, when I tried to use highcharts export modules, it is not compatible under StockChart.  In order to fix, we need to selectively import modules either from highcharts-release or highstock-release based on whether includeHighStock is enabled--Highstock version 2.1.10 now comes with its own modules folder.
Thanks!

**Comment by ahmadsoe** [comment]
Have you added the `exporting` option to `ember-cli-build.js`?
```
var app = new EmberApp(defaults, {
  emberHighCharts: {
    ---
    includeModules: ['exporting']
  }
});
```

**Comment by lvanngo** [comment]
I see that in the new version, you are copying files from bower instead of node_modules.  This should resolve the problem.  Thanks!
