### ISSUE TITLE
Error #16 while using both Highcharts and Highmaps

### ISSUE THREAD

**Issue by Naxum** [ahmadsoe/ember-highcharts#50]
Hey! First off, I love this addon and use it quite a bit now.

I've noticed a big problem when using Highcharts and Highmaps together, just enabling both in EmberApp options, you'll receive the [Highcharts error #16](http://www.highcharts.com/errors/16) when the page loads.

Turns out when you have already loaded `highcharts.js`, you're supposed to just load `modules/map.js` instead of adding `highmaps.js` as well (real intuitive, right?) I'm not positive if this applies to every Highwhatever, so I don't feel comfortable submitting a pull request (I also am fairly new to Ember and making addons for it), but here's my code:

index.js around line 20

```
if (options.includeHighMaps) {
  if (options.includeHighCharts) {
    app.import(app.bowerDirectory + '/highcharts/modules/map.src.js');
  } else {
    app.import(app.bowerDirectory + '/highcharts/highmaps.src.js');   
  }
}
```

This resolves getting [Highcharts error #16](http://www.highcharts.com/errors/16) every time the page loads. And to reiterate, I am only using Highcharts and Highmaps, so I don't know what other requirements there are to get multiple things working together.

**Comment by Naxum** [comment]
Oh! I just realized the bower modules folder has everything including the map.js module, so instead of my code one just needs to set up the emberHighChart options correctly. Maybe this could be mentioned somewhere?

```
emberHighCharts: {
  includeHighCharts: true,
  includeModules: ['map']
}
```

**Comment by ahmadsoe** [comment]
Or you can just disable HighCharts and enable HighMaps instead.
```
emberHighCharts: {
  includeHighCharts: false,
  includeHighMaps: true,
}
```
