### ISSUE TITLE
Verion 0.3.0 still shows the container warning

### ISSUE THREAD

**Issue by svkangal** [ahmadsoe/ember-highcharts#56]
Hi seems like  this.container to getOwner change has not made it to version 0.3.0. Installing the addon still gives me the old code.

https://github.com/ahmadsoe/ember-highcharts/commit/bda15752272e60728aa2c253132324c20b5e6025

**Comment by gregjopa** [comment]
Yes, version 0.3.0 does not contain this `getOwner()` change. We will be releasing 0.3.1 soon which will contain this change.

**Comment by ahmadsoe** [comment]
Just publish a new release `0.4.0`, the warning should be gone now.

**Comment by svkangal** [comment]
thanks for the quick update.
