### ISSUE TITLE
Release new version of ember-highcharts

### ISSUE THREAD

**Issue by gregjopa** [ahmadsoe/ember-highcharts#57]
@ahmadsoe I think we should cut a new release of this addon. Perhaps we should bump the version to 0.4.0 since moving the highcharts dependency to npm is a major change.

Let me know your thoughts.

**Comment by ahmadsoe** [comment]
@gregjopa I just publish a new release `0.4.0`.

**Comment by gregjopa** [comment]
Thanks @ahmadsoe! I just tested out version `0.4.0` and it works great for me.
