### ISSUE TITLE
trying to use modules, solid gauge does not work

### ISSUE THREAD

**Issue by SSS2557** [ahmadsoe/ember-highcharts#60]
Uncaught TypeError: Parent is not a function

I tried many combinations of config but did not work.
Currently using this config:

emberHighCharts: {
      includeHighCharts: true,
      includeModules: ['solid-gauge']
    }

**Comment by SSS2557** [comment]
<img width="1435" alt="screen shot 2016-02-18 at 4 06 50 pm" src="https://cloud.githubusercontent.com/assets/4912467/13162421/b0713636-d659-11e5-8551-fdc0bf4fd54d.png">

**Comment by SSS2557** [comment]
For now, I added on the highcharts.src.js

`if(!Parent) {
            Parent = function () {
            };
        }`

**Comment by gregjopa** [comment]
I think highcharts-more.js is required to use the solid-guage module. Ex: http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/gauge-solid/

Try updating your config to: 
```js
    emberHighCharts: {
      includeHighCharts: true,
      includeHighChartsMore: true,
      includeModules: ['solid-gauge']
    }
```

Let me know if that solves your problem.

**Comment by SSS2557** [comment]
unfortunately no :(

I see ember build errors when i do that.

/source_map_concat-input_base_path-XJnjiS11.tmp/0/vendor/highcharts/highcharts/highcharts-more.src.js'  not found

**Comment by gregjopa** [comment]
Sounds like there may be an issue with the assets in your temp folder. Try running: `rm -rf dist tmp` and then restarting the ember server.

If that doesn't work then can you provide more info? Let me know the OS you're using, the version of ember-cli, and version of npm.

**Comment by SSS2557** [comment]
I always clean...so that doesn't work :(

Here is what I have:
version: 2.3.0
node: 0.10.38
os: darwin x64
npm: 1.4.28

**Comment by gregjopa** [comment]
I think the old version of Node is the problem. With node v0.10.x there was an issue with creating the correct path for highcharts-more. This issue has already been fixed in PR #59 but it hasn't been released yet. Can you try upgrading to a newer version of Node? Or installing this addon directly from the master branch? Ex: `npm install git://github.com/ahmadsoe/ember-highcharts.git#master`

**Comment by SSS2557** [comment]
Sure :)

I will glady give the master branch a shot and get back.
Unfortunately, trying newer version of Node is not an option for me due to constraints where I work at the moment as well as our dependencies

**Comment by SSS2557** [comment]
I confirm the previous issue is gone :) so solid gauge now works when i use master branch.
However, now I seem to have Uncaught TypeError: get(...).forEach is not a function :(

Not sure if this is related to my incorrect config as such.

I assume 'content' for the add-on would be series from the following object for solid gauge as well.
Please advice.

This is what i have

`chartOptions: {
    chart: {
      type: 'solidgauge',
      plotBackgroundColor: null,
      plotBorderWidth: 0,
      plotShadow: false,
      height: 77,
      width: 120,
      spacingBottom: 0,
      spacingTop: 0,
      spacingLeft: 0,
      spacingRight: 0,
      backgroundColor: null
    },

    pane: {
      center: ['50%', '85%'],
      size: '140%',
      startAngle: -90,
      endAngle: 90,
      background: {
        backgroundColor: '#EEE',
        innerRadius: '60%',
        outerRadius: '100%',
        shape: 'arc'
      }
    },

    tooltip: {
      enabled: false
    },
    credits: {
      enabled: false
    },

    // the value axis
    yAxis: {
      stops: [
        [0.1, 'rgba(2, 14, 101, 0.7)'],
        [0.2, 'rgba(2, 14, 101, 0.32)'],
        [0.3, 'rgba(255, 139, 18, 0.55)'],
        [0.5, 'rgba(142, 255, 18, 0.52)'],
        [0.65, 'rgba(86, 1, 255, 0.62)'],
        [0.85, 'rgba(0, 160, 152, 0.69)']
      ],
      currentMin: 0,
      currentMax: 15,
      lineWidth: 0,
      minorTickInterval: null,
      tickWidth: 0,
      labels: {
        y: 16
      }
    },
    title: {
      text: ''
    },
    series: [{
      name: 'Something',
      data: [8],
      dataLabels: {
        enabled: false
      },
      tooltip: {
        enabled: 'false'
      }
    }],

    plotOptions: {
      solidgauge: {
        dataLabels: {
          y: 5,
          borderWidth: 0,
          useHTML: true
        }
      }
    }
  }`

**Comment by SSS2557** [comment]
Update:

Master branch at the moment works :) 

Thanks

**Comment by gregjopa** [comment]
Good to hear. Version 0.4.1 just got released which includes the fix you need. Please use that instead of the master branch.
