### ISSUE TITLE
Is is possible to show highmaps and and highcharts in the same page?

### ISSUE THREAD

**Issue by arthur-zheng** [ahmadsoe/ember-highcharts#72]
Hello ember ninjas,

Recently I am trying to show highmaps in the a ember page which already has multiple highcharts. However after setting up the ember-cli-build.js according to the official guide. like(enabling highcharts and highmaps at the same time):

`emberHighCharts: { includeHighCharts: true, includeHighMaps: true }`

I got error in the browser console(latest chrome) says:

`highmaps.src.js:115Uncaught Error: Highcharts error #16: www.highcharts.com/errors/16`
`loader.js:171 Uncaught Error: Could not find module "ember-resolver" imported from "my-app/resolver"`

My versions: highcharts: 4.2.1, ember-cli: 2.3.0, ember: ~2.3.1, ember-highcharts: 0.4.3
Any ideas? Thank you so much!

**Additional Clue**
If you set `includeHighCharts: false, includeHighMaps: true`, it displays something.

**PS: How to reproduce:**
1. do a `ember new my-app` to create an empty project
2. install ember highcharts using `ember install ember-highcharts`
3. Insert this code into application.hbs already generated: 
`{{high-charts mode='Map' content=chartData chartOptions=chartOptions}}`
4. run the app see the error

**Comment by gregjopa** [comment]
Can you try changing your setup in ember-cli.build.js to:

```js
emberHighCharts: { includeHighCharts: false, includeHighMaps: true }
```

The `includeHighMaps` option should automatically include highCharts too. For example. the dummy app uses highcharts and highstock and only highstock needs to be enabled: https://github.com/ahmadsoe/ember-highcharts/blob/master/ember-cli-build.js.

**Comment by arthur-zheng** [comment]
Thanks @gregjopa. I just tried it. But it complains another error says 'Parent is not a constructor'.
<img width="595" alt="screen shot 2016-04-28 at 11 09 09 am" src="https://cloud.githubusercontent.com/assets/4089684/14896294/d850c31a-0d31-11e6-8573-71cbd1d013e3.png">

**Comment by gregjopa** [comment]
I just learned that if highcharts is already loaded then highmaps needs to be loaded as a plugin. Here are more details about this: http://www.highcharts.com/docs/maps/getting-started.

You can load highmaps as a plugin using the 'includeModules' option. Ex:
```js
var app = new EmberApp(defaults, {
  emberHighCharts: {
    includeHighCharts: true,
    includeModules: [
      'map'
    ]
  }
});
```

I added a highmaps example to the tests/dummy app in PR #73. Hopefully this example helps you get highmaps working correctly.

**Comment by arthur-zheng** [comment]
Thank you again @gregjopa!!! give me a moment to try it out and get back!

**Comment by SSS2557** [comment]
@gregjopa , just added a comment to the PR.

I had tried this out but thought we also had to include highmaps.

I see highcharts/modules/map.js and highcharts/highmaps.js

However, this only works when only map is included as a module

**Comment by gregjopa** [comment]
Thanks for the feedback. I updated the README in the PR based on your comment.

If you just need highmaps only then use the following:
```js
emberHighCharts: { 
  includeHighCharts: false, 
  includeHighMaps: true 
}
```

If you need to use both highcharts and highmaps then use the following:
```js
emberHighCharts: {
  includeHighCharts: true,
  includeModules: [
    'map'
  ]
}
```

**Comment by arthur-zheng** [comment]
Hi @gregjopa, as I verified, your solution is working perfectly in my project. You made my day!!!

**Comment by gregjopa** [comment]
@arthur-zheng good to hear 👍
