### ISSUE TITLE
allow specification of which version of highcharts, highstock, etc to use

### ISSUE THREAD

**Issue by SirZach** [ahmadsoe/ember-highcharts#74]
I haven't had time to debug why, but when I run `highstock` at version `4.2.3` my app crawls but using version `2.1.7` it runs fine. It would be great if in the `ember-cli-build.js` if I could specify which version of each highcharts library to use. Thanks!

**Comment by gregjopa** [comment]
This addon includes a blueprint to add [highcharts](https://www.npmjs.com/package/highcharts) to the package.json file: https://github.com/ahmadsoe/ember-highcharts/blob/master/blueprints/ember-highcharts/index.js#L7. After installing this addon you can update highcharts in your package.json file to whatever version you'd like to use.

**Comment by SirZach** [comment]
@gregjopa thanks! i guess the only problem I have is that the tagged versions of highcharts, https://github.com/highcharts/highcharts-dist/tree/master, doesn't include a version that has `highstock` at `2.1.7`

**Comment by SirZach** [comment]
I'll have to fork that repo and specify the versions I need. thanks!

**Comment by gregjopa** [comment]
@SirZach another option instead of forking is to not load highcharts with this addon. You can do this with the following code in your ember-cli-build.js file:
```js
var app = new EmberApp(defaults, {
  emberHighCharts: {
    includeHighCharts: false
  }
});
```

Then manually add the highstock version you need to the `vendor` folder in your app and load it into your app's asset pipeline that way.
