### ISSUE TITLE
Controller or Component?

### ISSUE THREAD

**Issue by danilovaz** [ahmadsoe/ember-highcharts#80]
This repository is compatible with ember 2.5.x? I ask this because I saw the documentation example Bar Chart and there exemplifies the use of a controller. I must use the controller or component to generate the graphics? I do not know if I was clear on the question ... anyway, thank you.

**Comment by gregjopa** [comment]
You can use either a controller or component. It's up to you. Here are some component examples: https://github.com/ahmadsoe/ember-highcharts/tree/master/tests/dummy/app/components

**Comment by danilovaz** [comment]
@gregjopa that's awesome! than'ks

**Comment by gregjopa** [comment]
Happy to help :)
