### ISSUE TITLE
Multiple solid gauge charts on page with different chart options

### ISSUE THREAD

**Issue by flameofzion** [ahmadsoe/ember-highcharts#85]
Hi, 

I need to have about 8 different solid gauge charts on a page to display various pieces of data. I have created a service to store the default options for the chart then added a method to that service that accepts the unique data pertaining to each gauge, overwrites the copy of the default options and returns the new array of chart options. This data that is overwritten is the yAxis.title.text, yAxis.min, and yAxis.max.

Then I made a component called gauge-chart that is given the chartOptions array and also the value for the gauge. My plan is to add an .on('init') method in the components/gauge-chart.js to take the value and add it to the chartData array and update the chart. 

My problem is that each chart is using 1 title. it seems to be whichever chartOptions is set last in the controller. 

Am I completely missing how to have multiple charts on a page and keep them updated when data values change? 

I thought I would ask the authors of this addon before scrapping and trying a different chart addon. 

Thanks for the addon and any help you can give!

**Comment by gregjopa** [comment]
You can use this addon to render several chart gauges on the same page. I think the `.on('init')` method is over complicating things. Instead, you just need to define separate `chartOptions` and `content` for each chart gauge. For example, in your controller/component your setup would something look like this:

```js
export default Ember.Controller.extend({

  chartOptions1: {
    chart: {
      type: 'solidgauge'
    },
    // add content
  },

  chartData1: [
    // add content
  ],


  chartOptions2: {
    chart: {
      type: 'solidgauge'
    },
    // add content
  },

  chartData2: [
    // add content
  ],


  chartOptions2: {
    chart: {
      type: 'solidgauge'
    },
    // add content
  },

  chartData2: [
    // add content
  ],

  // add chartOptions3, chartOptions4, etc

});
```

```handlebars
{{chart-solid-gauge content=chartData1 chartOptions=chartOptions1}}
{{chart-solid-gauge content=chartData2 chartOptions=chartOptions2}}
{{chart-solid-gauge content=chartData3 chartOptions=chartOptions3}}
```

First try and get things working with this approach. Then after that, you can dry things up. For example. if your `chartOptions` are very similar for all 8 chart gauges than they can all share the same chartOptions and you can make certain attributes of those configurable. You can do this by making chartOptions a computed property:

```js
export default Ember.Component.extend({

  chartOptions: Ember.computed(function () {

    return {
      chart: {
        type: 'solidgauge'
      },
      title: {
        text: this.get('title')
      },
      ...
    }

  })

  ...

});
```

```handlebars
{{chart-solid-gauge content=chartData1 chartOptions=chartOptions title="custom title 1"}}
```

**Comment by flameofzion** [comment]
Thanks @gregjopa!

I was getting frustrated with getting this to work. I really like the approach of the computed properties, thats essentially exactly what I wanted to do! I got it working now!

**Comment by gregjopa** [comment]
Happy to help!

**Comment by flameofzion** [comment]
I'm noticing that when the value for the gauge changes, the gauge resets to 0 then goes back up to the newly changed value. Is there a way to adjust the gauge at its current value and animate it to the new value, rather than going back to 0 first?

**Comment by gregjopa** [comment]
We currently call `redraw` when updating chart data: https://github.com/ahmadsoe/ember-highcharts/blob/master/addon/components/high-charts.js#L96. This is probably causing the gauge to redraw from 0 everytime. The tricky thing with updating chart data with highcharts is every chart type has different updating logic. This addon currently does not support every use case.

You can extend this component and override the `didReceiveAttrs()` method to have custom updating logic. I think you will need to call `point.update(num)` similar to this demo: http://www.highcharts.com/demo/gauge-solid

**Comment by flameofzion** [comment]
Its not the end of the world, would just be nice, I'll give that approach a try. Thanks again!
