### ISSUE TITLE
Callback for afterSetExtremes (zoom in on x Axis)

### ISSUE THREAD

**Issue by jandillmann** [ahmadsoe/ember-highcharts#87]
I created my own chart component like this:
```
import Highcharts from 'ember-highcharts/components/high-charts';

export default Highcharts.extend({
  chartOptions: {
    chart: {
      zoomType: 'x'
    },
    xAxis: {
      events : {
        afterSetExtremes: (event) => {
          console.log(this);
        }
      }
    }
  }
});
```
so I can reload more data when the user zooms in (like here: http://www.highcharts.com/stock/demo/lazy-loading)

In the example above, `this` seems to be the context of the ES6 module, and when using a normal JavaScript function
```
afterSetExtremes(event) {
  console.log(this);
}
```
`this` refers to the Highcharts-Object itself.

Preferably I would like to call an action on the component (e.g. `this.attrs.onZoom(event)`), but it seems impossible due to `this` not being the context of the component.

Is there another way to achieve reloading of more data using Ember Data?

**Comment by gregjopa** [comment]
Hey @jandillmann, you can use a computed property for `chartOptions` in your component to save the component context to a local variable.

```js
import Ember from 'ember';

export default Ember.Component.extend({
  chartOptions: Ember.computed(function () {

    var self = this;

    console.log('component context', self);
  
    return {
      chart: {
        zoomType: 'x'
      },
      xAxis: {
        events: {
          afterSetExtremes: (event) => {
            // ember component context
            console.log(self);

            // highcharts context
            console.log(this);
          }
        }
      }
    };

  })
});
```

Let me know if this resolves your issue.

**Comment by jandillmann** [comment]
D'oh, of course. Thanks, that does work.

**Comment by subbusgithub** [comment]
Hey @jandillmann, @gregjopa , I have run into a similar problem. I am not able to access the this object inside the aftersetextremes event call back in my library. Below is the code snipet. 

function Chart(container, live)
{
    //global hichart object
    this.hiChart = "";

    ///*code to set hichart options*/
    this.options =
    {
         xAxis:
        {
            events:
            {
                afterSetExtremes: this.cbAfterSetExtremes
            },
            //minRange: 3600 * 1000 // one hour 60 * 1000 //1 minute //
        },
           ..... /*other chart options go here*/
    }

Chart.prototype.cbAfterSetExtremes = function (e)
{
    //get the new minimum and maximum dates
    let fromDate = new Date(e.min);
    let toDate = new Date(e.max);

    //display loader
    this.hiChart.showLoading('<img src="/assets/processing.gif">'); /*This line throws the error*/
}

I have omitted the instantiation deliberately to keep the code short as the chart gets created properly when it loads for the first time. When the chart is instantiated the "hiChart" member of the class is initialised with the newly created Hichart object. When the event is fired the callback is hit but the showloading function is not being executed. 

Kindly explain if I can use the technique described in the above comment to solve this issue and if yes how how? as I have tried it and failed to get the desired output.

Thanks in advance.
