### ISSUE TITLE
Drilldown does not work when attribute is computed property

### ISSUE THREAD

**Issue by jandillmann** [ahmadsoe/ember-highcharts#90]
Setting the drilldown data inside a chart component directly (like in [the test/dummy app](https://github.com/ahmadsoe/ember-highcharts/blob/master/tests/dummy/app/components/chart-column-drilldown.js)) works, but if the drilldown property is set from outside (e.g. data loaded from the server) clicking on the column does not drill down to show the detailed data.

**Comment by gregjopa** [comment]
Are you trying to implement async drilldowns using the events.drilldown option like in this fiddle? http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/drilldown/async/

Can you post your code?

**Comment by jandillmann** [comment]
No, I was not, but this got me on the right path – thanks!
