### ISSUE TITLE
specify height

### ISSUE THREAD

**Issue by SirZach** [ahmadsoe/ember-highcharts#94]
It looks like the default height for highcharts is 400px, http://api.highcharts.com/highcharts#chart.height, but I'd like to specify different heights. `{{high-charts data=data options=options height=200}}`. Is there another way to do this?

**Comment by gregjopa** [comment]
You can specify different heights using `chartOptions`:
```js
  chartOptions: {
    chart: {
      type: 'bar',
      height: 800
    },
    title: {
      text: 'Fruit Consumption'
    },
```

**Comment by SirZach** [comment]
Apologies if I missed that in the highchart docs. Thanks!
