### ISSUE TITLE
Charts render but without any actual data points showing up

### ISSUE THREAD

**Issue by rmcsharry** [ahmadsoe/ember-highcharts#95]
Using Ember 2.7 I can get the component to work but not matter which of the example charts I try to render from the dummy app, all I see are the Title, series name but no actual data is rendering in the chart. No errors in the console or the log! Why are the charts all empty?

![image](https://cloud.githubusercontent.com/assets/1156100/18009285/d11fb8b6-6bab-11e6-8a9e-641d94cacfc3.png)

![image](https://cloud.githubusercontent.com/assets/1156100/18009177/732b44dc-6bab-11e6-8ce1-b2e858104600.png)

**Comment by gregjopa** [comment]
Does the same code work for you in ember 2.6?

The screenshot indicates that no chart data was passed into the "content" component parameter:
```hbs
{{log chartOptions}}
{{log chartData}}
{{high-charts chartOptions=chartOptions content=chartData}}
```
To debug this I'd recommend logging the values in the template w/ the log helper to make sure the data is passed in correctly:

**Comment by gregjopa** [comment]
I just tested this component with Ember 2.7 and it works fine (https://github.com/ahmadsoe/ember-highcharts/pull/96).

Let me know if you are still having this problem.

**Comment by rmcsharry** [comment]
@gregjopa Hi sorry I was away a few days. Thanks for checking and especially for pointing out that no chart data was being passed. I was convinced it was, but a mix up on my part was the cause, so if you hadn't mentioned that I would not have thought to check what was being passed in.

Thanks again, much appreciated!

**Comment by gregjopa** [comment]
Good to hear. Happy to help!

**Comment by rmcsharry** [comment]
@gregjopa Could you take a minute to look at this? Seems very strange to me.

http://stackoverflow.com/questions/39217777/emberjs-2-7-passing-data-down-into-a-component-is-failing

**Comment by rmcsharry** [comment]
Never mind, I figured it out.
